Repository phdljr/Trollo, pull requests merged in 2023-12, with the labels that each got.

#4 [#3] Feature/swagger - Swagger 의존성 추가
  build.gradle
Labels: enhancement

#22 Feature/config jpa auditing - Jpa Auditing 설정
  src/main/java/org/nbc/account/trollo/global/config/JpaConfig.java
  src/main/java/org/nbc/account/trollo/global/entity/BaseEntity.java
Labels: feature

#42 Feature/signup and login
  build.gradle
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/request/LoginReq.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/request/SignupReq.java
  src/main/java/org/nbc/account/trollo/domain/user/entity/User.java
  src/main/java/org/nbc/account/trollo/domain/user/repository/UserRepository.java
  src/main/java/org/nbc/account/trollo/domain/user/service/UserService.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/config/WebSecurityConfig.java
  src/main/java/org/nbc/account/trollo/global/dto/ApiResponse.java
  src/main/java/org/nbc/account/trollo/global/entity/Timestamped.java
  src/main/java/org/nbc/account/trollo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/nbc/account/trollo/global/jwt/JwtAuthorizationFilter.java
  src/main/java/org/nbc/account/trollo/global/jwt/JwtUtil.java
  src/main/java/org/nbc/account/trollo/global/security/UserDetailsImpl.java
  src/main/java/org/nbc/account/trollo/global/security/UserDetailsService.java
Labels: feature

#43 AWS_S3 bucket 폴더 생성 및 파일 생성
  src/main/java/org/nbc/account/trollo/s3/S3Config.java
  src/main/java/org/nbc/account/trollo/s3/S3Provider.java
Labels: feature

#51 [#49 #50]Feature/custom exception - 커스텀 예외 설정 및 도메인 명칭 수정
  src/main/java/org/nbc/account/trollo/domain/section/entity/Section.java
  src/main/java/org/nbc/account/trollo/global/exception/CustomException.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
  src/main/java/org/nbc/account/trollo/global/exception/GlobalExceptionHandler.java
Labels: feature, refactor

#52 [#47]Feat: Card 생성 기능 추가
  src/main/java/org/nbc/account/trollo/domain/board/entity/Board.java
  src/main/java/org/nbc/account/trollo/domain/board/exception/NotFoundBoardException.java
  src/main/java/org/nbc/account/trollo/domain/board/repository/BoardRepository.java
  src/main/java/org/nbc/account/trollo/domain/card/controller/CardController.java
  src/main/java/org/nbc/account/trollo/domain/card/dto/request/CardCreateRequestDto.java
  src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
  src/main/java/org/nbc/account/trollo/domain/card/repository/CardRepository.java
  src/main/java/org/nbc/account/trollo/domain/card/service/CardService.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/section/exception/NotFoundSectionException.java
  src/main/java/org/nbc/account/trollo/domain/section/exception/NotFoundSectionInBoardException.java
  src/main/java/org/nbc/account/trollo/domain/section/repository/ColumnRepository.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/userboard/entity/UserBoard.java
  src/main/java/org/nbc/account/trollo/domain/userboard/entity/UserBoardId.java
  src/main/java/org/nbc/account/trollo/domain/userboard/entity/UserBoardRole.java
  src/main/java/org/nbc/account/trollo/domain/userboard/exception/NotFoundUserBoardException.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
Labels: feature

#64 [#14] Feature/refactor signup and login
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/request/LoginReq.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/request/SignupReq.java
  src/main/java/org/nbc/account/trollo/domain/user/entity/User.java
  src/main/java/org/nbc/account/trollo/domain/user/exception/UserDomainException.java
  src/main/java/org/nbc/account/trollo/domain/user/service/UserService.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/config/WebSecurityConfig.java
  src/main/java/org/nbc/account/trollo/global/dto/ApiResponse.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
  src/main/java/org/nbc/account/trollo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/nbc/account/trollo/global/jwt/JwtAuthorizationFilter.java
  src/main/java/org/nbc/account/trollo/global/jwt/JwtUtil.java
  src/main/java/org/nbc/account/trollo/global/security/UserDetailsService.java
Labels: refactor

#63 [#53]Feature/card read - 카드 단일 조회
  src/main/java/org/nbc/account/trollo/domain/card/controller/CardController.java
  src/main/java/org/nbc/account/trollo/domain/card/dto/response/CardReadResponseDto.java
  src/main/java/org/nbc/account/trollo/domain/card/exception/ForbiddenAccessCardException.java
  src/main/java/org/nbc/account/trollo/domain/card/exception/NotFoundCardException.java
  src/main/java/org/nbc/account/trollo/domain/card/mapper/CardMapper.java
  src/main/java/org/nbc/account/trollo/domain/card/service/CardService.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#71 [#55]Feature/card read by section - Section 기준으로 카드 조회
  src/main/java/org/nbc/account/trollo/domain/card/controller/CardController.java
  src/main/java/org/nbc/account/trollo/domain/card/dto/request/CardCreateRequestDto.java
  src/main/java/org/nbc/account/trollo/domain/card/dto/response/CardAllReadResponseDto.java
  src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
  src/main/java/org/nbc/account/trollo/domain/card/mapper/CardMapper.java
  src/main/java/org/nbc/account/trollo/domain/card/repository/CardRepository.java
  src/main/java/org/nbc/account/trollo/domain/card/service/CardService.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#56 [#32] Comment 구현 수정
  src/main/java/org/nbc/account/trollo/domain/comment/CommentController.java
  src/main/java/org/nbc/account/trollo/domain/comment/CommentService.java
  src/main/java/org/nbc/account/trollo/domain/comment/dto/req/CommentDeleteReq.java
  src/main/java/org/nbc/account/trollo/domain/comment/dto/req/CommentSaveReq.java
  src/main/java/org/nbc/account/trollo/domain/comment/dto/res/CommentDeleteRes.java
  src/main/java/org/nbc/account/trollo/domain/comment/dto/res/CommentSaveRes.java
  src/main/java/org/nbc/account/trollo/domain/comment/entity/CommentEntity.java
  src/main/java/org/nbc/account/trollo/domain/user/repository/UserRepository.java
  src/main/java/org/nbc/account/trollo/s3/S3Validator.java
Labels: feature, invalid, question, refactor

#79 Feature/refactor signup and login
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/entity/User.java
Labels: feature

#80 Breaking: 회의 내용을 반영한 코드 수정 작업
  src/main/java/org/nbc/account/trollo/domain/card/controller/CardController.java
  src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
  src/main/java/org/nbc/account/trollo/domain/card/repository/CardRepository.java
  src/main/java/org/nbc/account/trollo/domain/card/service/CardService.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/request/LoginReq.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/request/SignupReq.java
  src/main/java/org/nbc/account/trollo/domain/user/entity/User.java
  src/main/java/org/nbc/account/trollo/domain/user/exception/UserDomainException.java
  src/main/java/org/nbc/account/trollo/domain/user/service/UserService.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
  src/main/java/org/nbc/account/trollo/global/config/S3Config.java
  src/main/java/org/nbc/account/trollo/global/config/WebSecurityConfig.java
  src/main/java/org/nbc/account/trollo/global/dto/ApiResponse.java
  src/main/java/org/nbc/account/trollo/global/entity/BaseEntity.java
  src/main/java/org/nbc/account/trollo/global/entity/Timestamped.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
  src/main/java/org/nbc/account/trollo/global/exception/GlobalExceptionHandler.java
  src/main/java/org/nbc/account/trollo/global/jwt/JwtAuthorizationFilter.java
  src/main/java/org/nbc/account/trollo/global/jwt/JwtUtil.java
  src/main/java/org/nbc/account/trollo/global/security/UserDetailsImpl.java
  src/main/java/org/nbc/account/trollo/global/security/UserDetailsService.java
  src/main/java/org/nbc/account/trollo/global/util/S3Provider.java
  src/main/java/org/nbc/account/trollo/global/util/S3Validator.java
Labels: refactor, style

#85 !HOTFIX: UserBoardId.class가 적용안된 상황 수정
  src/main/java/org/nbc/account/trollo/domain/board/entity/Board.java
  src/main/java/org/nbc/account/trollo/domain/section/entity/Section.java
  src/main/java/org/nbc/account/trollo/domain/userboard/entity/UserBoard.java
Labels: bug

#74 [#61] Feature/card update - 카드 업데이트 기능 구현
  src/main/java/org/nbc/account/trollo/domain/card/controller/CardController.java
  src/main/java/org/nbc/account/trollo/domain/card/dto/request/CardUpdateRequestDto.java
  src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
  src/main/java/org/nbc/account/trollo/domain/card/service/CardService.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature, refactor, style

#98 [#75] Feature/read invitations
  src/main/java/org/nbc/account/trollo/domain/invitation/controller/InvitationController.java
  src/main/java/org/nbc/account/trollo/domain/invitation/dto/response/InvitationRes.java
  src/main/java/org/nbc/account/trollo/domain/invitation/exception/InvitationDomainException.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/InvitationService.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/impl/InvitationServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/userboard/entity/UserBoard.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#101 [#100]Feat: 사용자가 보드에 속하는지 판단하는 로직 추가
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/userboard/exception/ForbiddenAccessBoardException.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#87 [#17]Feat: checklist-create
  src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
  src/main/java/org/nbc/account/trollo/domain/card/exception/ForbiddenAccessBoardException.java
  src/main/java/org/nbc/account/trollo/domain/checklist/controller/CheckListController.java
  src/main/java/org/nbc/account/trollo/domain/checklist/dto/request/CheckListRequestDto.java
  src/main/java/org/nbc/account/trollo/domain/checklist/entity/CheckList.java
  src/main/java/org/nbc/account/trollo/domain/checklist/repository/CheckListRepository.java
  src/main/java/org/nbc/account/trollo/domain/checklist/service/CheckListService.java
  src/main/java/org/nbc/account/trollo/domain/checklist/service/impl/CheckListServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
Labels: feature

#93 [#19]Feat/checklist delete
  src/main/java/org/nbc/account/trollo/domain/checklist/controller/CheckListController.java
  src/main/java/org/nbc/account/trollo/domain/checklist/entity/CheckList.java
  src/main/java/org/nbc/account/trollo/domain/checklist/exception/NotFoundCheckListException.java
  src/main/java/org/nbc/account/trollo/domain/checklist/service/CheckListService.java
  src/main/java/org/nbc/account/trollo/domain/checklist/service/impl/CheckListServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#108 [#107]Feature/card delete - Card 삭제 기능 구현
  src/main/java/org/nbc/account/trollo/domain/card/controller/CardController.java
  src/main/java/org/nbc/account/trollo/domain/card/service/CardService.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
Labels: feature, style
