Repository phdljr/Trollo, pull requests merged in 2024-01, with the labels that each got.

#103 Feature/reject invitation
  src/main/java/org/nbc/account/trollo/domain/invitation/controller/InvitationController.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/InvitationService.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/impl/InvitationServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
Labels: feature

#117 [#116]Feat: Card 순서 변경 기능 구현
  src/main/java/org/nbc/account/trollo/domain/card/controller/CardController.java
  src/main/java/org/nbc/account/trollo/domain/card/converter/CardSequenceDirection.java
  src/main/java/org/nbc/account/trollo/domain/card/converter/StringToCardSequenceDirectionConverter.java
  src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
  src/main/java/org/nbc/account/trollo/domain/card/exception/BadCardSequenceDirectionRequestException.java
  src/main/java/org/nbc/account/trollo/domain/card/exception/ForbiddenChangeCardSequenceException.java
  src/main/java/org/nbc/account/trollo/domain/card/exception/IllegalChangeSameCardException.java
  src/main/java/org/nbc/account/trollo/domain/card/service/CardService.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/config/WebConfig.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#106 Feat/notification get
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/notification/controller/NotificationController.java
  src/main/java/org/nbc/account/trollo/domain/notification/dto/response/NotificationResponseDto.java
  src/main/java/org/nbc/account/trollo/domain/notification/entity/Notification.java
  src/main/java/org/nbc/account/trollo/domain/notification/entity/NotificationType.java
  src/main/java/org/nbc/account/trollo/domain/notification/event/CardEvent.java
  src/main/java/org/nbc/account/trollo/domain/notification/event/NotificationListeneer.java
  src/main/java/org/nbc/account/trollo/domain/notification/exception/NotFoundUnreadStatusException.java
  src/main/java/org/nbc/account/trollo/domain/notification/repository/NotificationRepository.java
  src/main/java/org/nbc/account/trollo/domain/notification/service/NotifiactionService.java
  src/main/java/org/nbc/account/trollo/domain/notification/service/impl/NotificationServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/userboard/repository/UserBoardRepository.java
  src/main/java/org/nbc/account/trollo/domain/usernotification/entity/UserNotification.java
  src/main/java/org/nbc/account/trollo/domain/usernotification/entity/UserNotificationId.java
  src/main/java/org/nbc/account/trollo/domain/usernotification/entity/UserNotificationStatus.java
  src/main/java/org/nbc/account/trollo/domain/usernotification/repository/UserNotificationRepository.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#120 Style: 코드 정리, 쓰지 않는 코드 삭제
  src/main/java/org/nbc/account/trollo/domain/invitation/controller/InvitationController.java
  src/main/java/org/nbc/account/trollo/domain/invitation/entity/Invitation.java
  src/main/java/org/nbc/account/trollo/domain/invitation/entity/InvitationId.java
  src/main/java/org/nbc/account/trollo/domain/invitation/exception/InvitationDomainException.java
  src/main/java/org/nbc/account/trollo/domain/invitation/repository/InvitationRepository.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/InvitationService.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/impl/InvitationServiceImpl.java
Labels: style

#121 Feature/read my page
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/response/MyPageRes.java
  src/main/java/org/nbc/account/trollo/domain/user/service/UserService.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/config/WebSecurityConfig.java
Labels: feature

#125 [#123]Feat: Card 빈 색션으로 이동 기능 구현
  src/main/java/org/nbc/account/trollo/domain/card/controller/CardController.java
  src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
  src/main/java/org/nbc/account/trollo/domain/card/exception/IllegalMoveToSectionException.java
  src/main/java/org/nbc/account/trollo/domain/card/repository/CardRepository.java
  src/main/java/org/nbc/account/trollo/domain/card/service/CardService.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#119 [#118]Feat/ 카드 조회시 체크리스트 추가
  src/main/java/org/nbc/account/trollo/domain/card/dto/response/CardReadResponseDto.java
  src/main/java/org/nbc/account/trollo/domain/card/mapper/CardMapper.java
  src/main/java/org/nbc/account/trollo/domain/checklist/dto/response/CheckListResponseDto.java
  src/main/java/org/nbc/account/trollo/domain/checklist/repository/CheckListRepository.java
Labels: feature

#136 [#124]Feat: 비밀번호 수정
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/request/PasswordUpdateReq.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/request/UserInfoUpdateReq.java
  src/main/java/org/nbc/account/trollo/domain/user/entity/User.java
  src/main/java/org/nbc/account/trollo/domain/user/service/UserService.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#139 [#112]Feat: 회원 탈퇴
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/service/UserService.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#140 [#53]Feat: 카드 단일 조회 시, 체크리스트 조회 기능 구현
  src/main/java/org/nbc/account/trollo/domain/card/dto/response/CardReadResponseDto.java
  src/main/java/org/nbc/account/trollo/domain/card/entity/Card.java
  src/main/java/org/nbc/account/trollo/domain/card/mapper/CardMapper.java
  src/main/java/org/nbc/account/trollo/domain/card/service/impl/CardServiceImpl.java
  src/main/java/org/nbc/account/trollo/domain/checklist/dto/response/CheckListResponseDto.java
Labels: feature

#144 보드에 초대한 사용자 초대 취소하기
  src/main/java/org/nbc/account/trollo/domain/invitation/controller/InvitationController.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/InvitationService.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/impl/InvitationServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/exception/ErrorCode.java
Labels: feature

#143 [#142]Feat: MethodArgumentNotValidException handler DTO 추가
  src/main/java/org/nbc/account/trollo/global/dto/BeanValidationErrorResponseDto.java
  src/main/java/org/nbc/account/trollo/global/exception/GlobalExceptionHandler.java
Labels: feature

#138 #27 s3 검증기능 및 파일 업로드 삭제 기능 추가
  src/main/java/org/nbc/account/trollo/domain/comment/controller/CommentController.java
  src/main/java/org/nbc/account/trollo/domain/comment/dto/req/CommentGetReqUser.java
  src/main/java/org/nbc/account/trollo/domain/comment/dto/req/CommentGetUserReq.java
  src/main/java/org/nbc/account/trollo/domain/comment/dto/res/CommentGetResUser.java
  src/main/java/org/nbc/account/trollo/domain/comment/dto/res/CommentGetUserRes.java
  src/main/java/org/nbc/account/trollo/domain/comment/mapper/CommentServiceMapper.java
  src/main/java/org/nbc/account/trollo/domain/comment/repository/CommentRepository.java
  src/main/java/org/nbc/account/trollo/domain/comment/service/CommentService.java
  src/main/java/org/nbc/account/trollo/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/util/S3Provider.java
  src/main/java/org/nbc/account/trollo/global/util/S3Validator.java
Labels: feature, style

#149 [#114]Feat :로그아웃
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/service/UserService.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
Labels: feature

#153 [#97] 초대 목록 조회에 보드명 뜨게 수정
  src/main/java/org/nbc/account/trollo/domain/invitation/controller/InvitationController.java
  src/main/java/org/nbc/account/trollo/domain/invitation/dto/response/InvitationRes.java
  src/main/java/org/nbc/account/trollo/domain/invitation/dto/response/InvitationsRes.java
  src/main/java/org/nbc/account/trollo/domain/invitation/dto/response/ReceivedInvitationRes.java
  src/main/java/org/nbc/account/trollo/domain/invitation/dto/response/SentInvitationRes.java
  src/main/java/org/nbc/account/trollo/domain/invitation/dto/response/UserBoardRes.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/InvitationService.java
  src/main/java/org/nbc/account/trollo/domain/invitation/service/impl/InvitationServiceImpl.java
Labels: refactor

#156 Feature/read my page
  src/main/java/org/nbc/account/trollo/domain/user/controller/UserController.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/response/BoardRes.java
  src/main/java/org/nbc/account/trollo/domain/user/dto/response/MyPageRes.java
  src/main/java/org/nbc/account/trollo/domain/user/service/impl/UserServiceImpl.java
Labels: refactor

#169 [#163]Feat: S3에 파일 저장 후 파일 경로 및 파일 이름 저장
  src/main/java/org/nbc/account/trollo/domain/S3File/controller/S3FileController.java
  src/main/java/org/nbc/account/trollo/domain/S3File/entity/S3File.java
  src/main/java/org/nbc/account/trollo/domain/S3File/repository/S3FileRepository.java
  src/main/java/org/nbc/account/trollo/domain/S3File/service/S3FileService.java
  src/main/java/org/nbc/account/trollo/domain/S3File/service/impl/S3FileServiceImpl.java
  src/main/java/org/nbc/account/trollo/global/util/S3Provider.java
Labels: feature
